#!/usr/bin/env tsx
/**
 * Generate docs/reference/tool-coverage.md from tools/registry.ts + test/ MCP calls.
 *
 * A tool is invoked when a test sends it through MCP:
 *   callTool("name") / callToolJson("name") / client.callTool("name")
 *   callTool(envOrUrl, "name")  (name as 2nd/3rd string literal)
 *   tools/call with name: "name"
 *
 * Name-only mentions (toolset tables, description-quality) do not count.
 * callTool(variable) loops are missed unless the name is also a literal in that call.
 *
 * Run with: npm run docs:tools
 */

import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

import { allTools, TOOLSET_DEFINITIONS } from "../tools/registry.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "..");
const TEST_DIR = join(REPO_ROOT, "test");
const OUT_PATH = join(REPO_ROOT, "docs", "reference", "tool-coverage.md");

const SKIP_FILES = new Set(["tool-description-quality.test.ts"]);

const GROUP_ORDER = [
  "projects",
  "repositories",
  "branches",
  "groups",
  "merge_requests",
  "issues",
  "labels",
  "workitems",
  "ci",
  "pipelines",
  "milestones",
  "wiki",
  "releases",
  "tags",
  "users",
  "variables",
  "webhooks",
  "search",
  "dependency_proxy",
  "vulnerabilities",
  "orbit",
];

const GROUP_TITLE: Record<string, string> = {
  merge_requests: "Merge Requests",
  issues: "Issues",
  repositories: "Projects & Files",
  branches: "Branches & Commits",
  projects: "Projects & Namespaces",
  labels: "Labels",
  ci: "CI Lint",
  groups: "Groups",
  pipelines: "Pipelines, Jobs & Deployments",
  milestones: "Milestones",
  wiki: "Wiki",
  releases: "Releases",
  tags: "Tags",
  users: "Users & Events",
  workitems: "Work Items",
  webhooks: "Webhooks",
  search: "Search",
  variables: "Variables",
  dependency_proxy: "Dependency Proxy",
  vulnerabilities: "Vulnerabilities",
  orbit: "GitLab Orbit",
  meta: "Meta & GraphQL",
};

const CANARY_INVOKED = [
  "list_project_variables",
  "orbit_query",
  "list_pipeline_schedules",
  "search_code",
];

const MIN_INVOKED = 146;

function walkTestFiles(dir: string): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    const stat = statSync(full);
    if (stat.isDirectory()) {
      out.push(...walkTestFiles(full));
      continue;
    }
    if (/\.(ts|js)$/.test(name) && !SKIP_FILES.has(name)) {
      out.push(full);
    }
  }
  return out;
}

function repoPath(abs: string): string {
  return relative(REPO_ROOT, abs).split("\\").join("/");
}

function collectInvocations(toolNames: ReadonlySet<string>): Map<string, string[]> {
  const hits = new Map<string, string[]>();
  for (const name of toolNames) {
    hits.set(name, []);
  }

  function add(name: string, file: string): void {
    const list = hits.get(name);
    if (!list || list.includes(file)) {
      return;
    }
    list.push(file);
  }

  for (const abs of walkTestFiles(TEST_DIR)) {
    const text = readFileSync(abs, "utf8");
    const rel = repoPath(abs);

    for (const match of text.matchAll(/\bcallTool[A-Za-z]*\(/g)) {
      const start = match.index + match[0].length;
      const window = text.slice(start, start + 400);
      const literals = [...window.matchAll(/['"`]([a-z][a-z0-9_]*)['"`]/g)].map(item => item[1]);
      for (const lit of literals.slice(0, 3)) {
        if (toolNames.has(lit)) {
          add(lit, rel);
        }
      }
    }

    if (text.includes("tools/call")) {
      for (const match of text.matchAll(/\bname\s*:\s*['"`]([a-z][a-z0-9_]*)['"`]/g)) {
        if (toolNames.has(match[1])) {
          add(match[1], rel);
        }
      }
    }
  }

  for (const list of hits.values()) {
    list.sort();
  }
  return hits;
}

function percent(invoked: number, total: number): string {
  if (total === 0) {
    return "0.0%";
  }
  return `${((invoked / total) * 100).toFixed(1)}%`;
}

function toolDocsHref(groupId: string, toolName: string): string {
  const slug = groupId.replace(/_/g, "-");
  return `../tools/${slug}.md#${toolName}`;
}

function formatFiles(files: string[]): string {
  return files.map(file => `\`${file}\``).join(", ");
}

function buildMarkdown(
  toolNames: string[],
  hits: Map<string, string[]>,
  grouped: Array<{ id: string; tools: string[] }>
): string {
  const invokedCount = toolNames.filter(name => (hits.get(name) ?? []).length > 0).length;
  const lines: string[] = [
    "# Tool invocation coverage",
    "",
    "<!-- Generated by scripts/generate-tool-coverage.ts. Do not edit. -->",
    "",
    "This is **MCP `tools/call` coverage**, not GitLab REST coverage and not line coverage.",
    "",
    "A tool counts as invoked when a test sends that name through MCP (`callTool` / `callToolJson` / `callToolAsync` / `client.callTool`, or a `tools/call` payload with `name: \"…\"`). Listing a name in a toolset filter or description-quality test does not count. `test:live` (`test/validate-api.js`) is a REST smoke check and is not included.",
    "",
    "| | |",
    "| --- | ---: |",
    `| Tools | ${toolNames.length} |`,
    `| Invoked | ${invokedCount} |`,
    `| Coverage | ${percent(invokedCount, toolNames.length)} |`,
    "",
    "## By toolset",
    "",
    "| Toolset | Invoked | Total | Coverage |",
    "| --- | ---: | ---: | ---: |",
  ];

  for (const group of grouped) {
    const invoked = group.tools.filter(name => (hits.get(name) ?? []).length > 0).length;
    const title = GROUP_TITLE[group.id] ?? group.id;
    lines.push(
      `| [${title}](#${group.id}) | ${invoked} | ${group.tools.length} | ${percent(invoked, group.tools.length)} |`
    );
  }

  lines.push("");

  for (const group of grouped) {
    const title = GROUP_TITLE[group.id] ?? group.id;
    lines.push(`## ${title}`);
    lines.push("");
    lines.push(`<a id="${group.id}"></a>`);
    lines.push("");
    for (const name of group.tools) {
      const files = hits.get(name) ?? [];
      const link = `[\`${name}\`](${toolDocsHref(group.id, name)})`;
      if (files.length > 0) {
        lines.push(`- [x] ${link} — ${formatFiles(files)}`);
      } else {
        lines.push(`- [ ] ${link}`);
      }
    }
    lines.push("");
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

function assertDetectorHealthy(hits: Map<string, string[]>, invokedCount: number): void {
  if (invokedCount < MIN_INVOKED) {
    throw new Error(
      `scanner found ${invokedCount} invoked tools; expected at least ${MIN_INVOKED} (detector probably broken)`
    );
  }
  for (const name of CANARY_INVOKED) {
    if ((hits.get(name) ?? []).length === 0) {
      throw new Error(`canary tool ${name} was not detected as invoked (detector probably broken)`);
    }
  }
}

function main(): void {
  const toolNames = allTools.map(tool => tool.name);
  const toolNameSet = new Set(toolNames);
  const hits = collectInvocations(toolNameSet);
  const invokedCount = toolNames.filter(name => (hits.get(name) ?? []).length > 0).length;
  assertDetectorHealthy(hits, invokedCount);

  const categorized = new Set<string>();
  const grouped: Array<{ id: string; tools: string[] }> = [];
  for (const id of GROUP_ORDER) {
    const definition = TOOLSET_DEFINITIONS.find(item => item.id === id);
    if (!definition) {
      throw new Error(`GROUP_ORDER lists '${id}' but TOOLSET_DEFINITIONS does not`);
    }
    const tools = [...definition.tools];
    for (const name of tools) {
      categorized.add(name);
    }
    grouped.push({ id, tools });
  }

  const meta = toolNames.filter(name => !categorized.has(name));
  if (meta.length > 0) {
    grouped.push({ id: "meta", tools: meta });
  }

  writeFileSync(OUT_PATH, buildMarkdown(toolNames, hits, grouped));
  console.log(
    `generated docs/reference/tool-coverage.md — ${invokedCount}/${toolNames.length} (${percent(invokedCount, toolNames.length)})`
  );
}

main();
